# Generated by Django 4.1.4 on 2022-12-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_product_user_product_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='product_quantity',
        ),
    ]
