# Generated by Django 4.1.4 on 2022-12-30 17:44

from django.db import migrations, models
import produtos.models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_rename_quantity_product_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to=produtos.models.upload_img, verbose_name='Imagem'),
        ),
    ]
