# Generated by Django 4.1.4 on 2022-12-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_product_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
