# Generated by Django 4.1.4 on 2022-12-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_remove_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='produtos.product', verbose_name='Produtos'),
        ),
    ]
