# Generated by Django 4.1.4 on 2023-01-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_remove_cart_products_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
