# Generated by Django 4.1.4 on 2023-01-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_remove_cart_quantity_remove_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.IntegerField(),
        ),
    ]
